name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform-validate-init-plan:
    name: Terraform Validate, Init, and Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: ./tfplan

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: terraform-validate-init-plan
    steps:
    - name: Waiting for approval
      run: |
        echo "Please approve or reject the plan."
        echo "This step is waiting for manual approval."
        echo "::pause::"

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan
        path: ./tfplan

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Apply
      run: terraform apply tfplan
